import type { Metadata } from "next";
import "../globals.css";
import type { ReactNode } from 'react';
import Sidebar from "@/components/shared/SideBar";
import Header from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AccountLayout({ children,  }: { children: ReactNode }) {
 
  return (
    <div className="flex min-h-screen">
      <div className="w-[10%] bg-slate-800 text-white">
        <Sidebar />
      </div>
      
      <div className="w-[90%] bg-gray-100">
        <Header />
        {children}
      </div>
    </div>
  );
}
